openapi: 3.0.3
info:
  title: sample_api_server
  description: this is a sample python API server 
  version: 1.0.0
servers: 
  - url: http://localhost:1001/api/v1

paths:
  /call_sample_api:
    post:
      parameters:
        - name: token
          in: header
          description: token
          required: true
          schema: 
            type: string
      responses: 
        200:
          description: Success
        500:
          description: Internal Server Error

  /get_predicted_file:
    post:
      parameters:
        - name: token_2
          in: header
          description: token
          required: true
          schema: 
            type: string
      responses: 
        200:
          description: Success
        500:
          description: Internal Server Error